package:
    name: eofs
    version: 0.5.0

source:
    git_url: git://github.com/ajdawson/eofs.git
    git_tag: v0.5.0

build:
    number: 1

    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy

test:
    requires:
        - nose
    imports:
        - eofs

about:
    home: http://ajdawson.github.io/eofs/
    license: GPL v3
