package:
    name: windspharm
    version: 1.3.2

source:
    git_url: git://github.com/ajdawson/windspharm.git
    git_tag: v1.3.2

build:
    number: 1
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - pyspharm

test:
    requires:
        - nose
    imports:
        - windspharm

about:
    home: http://ajdawson.github.io/windspharm/
    license: MIT
